# Build settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME', '.gitignore']


# Site settings
title: DevFest Nordeste 2014
email: contato@devfestne.com.br
description: "DevFest Nordeste é o maior evento de tecnologias Google do Nordeste"
baseurl: ""
url: "http://2014.devfestne.com.br"
permalink: /blog/:title
googleAnalyticsTrackingId: "UA-49492619-3"
googleAnalyticsSiteUrl: "devfestne.com.br"

# Organizer Info
organizerName: "DevFest NE 2014"
organizerAlternateName: "Equipe DevFest Nordeste 2014"
organizerDescription: "Comunidades geek abertas e voluntárias que criam projetos excitantes e compartilham experiência com tecnologia Google com paixão."
organizerEmail: "contato@devfestne.com.br"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://ne.devfest.com.br/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@DevFestNE"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://bit.ly/devfestne-call"
c4sponsorsUrl: "/blog/patrocinador/"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Palestrantes"}
 - {permalink: "/team/", text: "Equipe"}
 - {permalink: "/logistics/", text: "Logística"}
 #- {permalink: "/#buy-tickets", text: "Inscrições"}
 #- {link: "https://docs.google.com/forms/d/1yhp0xcYwsggotXGQRr1JnRR-USCxp-AlDM4pprfDgHs/viewform?usp=send_form", text: "Inscrições"}
 - {permalink: "/partners/", text: "Parceiros"}
 - {link: "https://developers.google.com", text: "Desenvolvedores"}
bottomNavigationLinks:
# - {link: "http://bit.ly/devfestne-call", text: "Seja um palestrante"}
rightNavigationButtons:
# - {link: "http://bit.ly/devfestne-call", text: "Seja um palestrante"}

# Hero Block
heroTitle: "GDG DevFest <typeout> 2014"
eventDate: "18 de outubro de 2014"
typeoutTextValues: '"", "Nordeste", "Aracaju", "João Pessoa", "Fortaleza", "Recife", "Maceió"'
heroButtons:
 #- {url: "http://bit.ly/devfestne-call", text: "Seja um palestrante"}
 #- {url: "http://2014.devfestne.com.br/blog/patrocinador/", text: "Seja um patrocinador"}
 #- {url: "https://doity.com.br/devfest-nordeste-2014", text: "Inscreva-se!"}
 #- {url: "https://docs.google.com/forms/d/1yhp0xcYwsggotXGQRr1JnRR-USCxp-AlDM4pprfDgHs/viewform?usp=send_form", text: "Inscrições esgotadas! Entre na lista de espera!"}
 - {url: "https://www.doity.com.br/devfest-nordeste-2014/certificados", text: "Certificados disponíveis"}

# About Block
aboutTitle: "Sobre GDG DevFest"
aboutBlock:
 - {title: "Conferência", image: "conference.jpg", text: "O maior evento do Nordeste relacionado ao Google cuidadosamente elaborado para você da comunidade GDG! Palestrantes impressionantes e muita diversão!" }
 - {title: "Palestras", image: "workshop.jpg", text: "Dia inteiro de palestras, Android, Chrome e Cloud. Venha domar a sua tecnologia favorita!" }
 - {title: "Happy DevFest Hour", image: "hackathon.jpg", text: "Depois de um dia inteiro de conteúdos incríveis, é hora de socializar!" }

# Statistic Block
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "participantes", detail: "de todo Brasil"}
 - {count: "12", specialCharacter: "+", info: "horas", detail: "de pura tecnologia Google"}
 - {count: "21", specialCharacter: "+", info: "palestrantes", detail: "de todo Brasil"}
 - {count: "2", specialCharacter: "", info: "trilhas paralelas", detail: "mais lounge de entretenimento"}

# Latest News Block
latestNewsTitle: "Últimas notícias"

# Rockstar Speakers Block
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Palestrantes rockstar"
rockstarSpeakersButtonText: "Veja todos palestrantes"

# Location Block
locationBlockTitle: "Local"
eventLocationName: "Radisson Hotel"
eventLocationLink: "http://www.radisson.com/aracaju-hotel-br-29055-180/braracaj"
eventStreetAddress: "Rua Dr. Bezerra de Menezes, 40"
eventAddressLocality: "Aracaju"
eventAddressLocalityRegion: "Sergipe"
eventPostalCode: "49035240"
eventAddressCountry: "Brasil"
eventStartTime: "2014-10-18T08:00"
eventDoorTime: "07:30"
eventEndTime: "2014-10-24T20:00"
eventPlaceCoordinates: "-10.976712,-37.040825,17"
mapCenterCoordinates: "-10.976712,-37.040825,17"
mapMobileCenterCoordinates: "-10.976712,-37.040825,17"

# Venue Block
venueBlockTitle: "Venue"
venueTitle: "Radisson Hotel"
venueFeatures: ["2 salas de apresentação", "Localizado na Orla de Atalaia"]

# Tweets Feed Block
tweetsFeedTitle: "Quais as novidades?"
twitterHashTag: "devfestnordeste"
twitterFeed: "http://gdgjp.org.br/old/twitterApp/get_timeline.php?c=10&cache_interval=900"

# Partners Block
partnersTitle: "Parceiros"
partnersC4sponsorsButton: "Seja um patrocinador"

# Organizers Block
organizersTitle: "Organizadores"

# Subscribe Block
subscribeTitle: "Acompanhe as novidades"
subscribeAction: "http://devfestne.us8.list-manage.com/subscribe/post?u=89545d81cc2471a50c83a319d&amp;id=bc6da73bc8"
subscribeInfo: "O DevFest Nordeste não enviará spam ao seu email. Todas as comunicações serão sobre o evento."

# Buy Tickets Block
buyTicketsTitle: "Inscrições"
ticketsOffers:
 -
  name: "Estudantes"
  price: "R$ 25"
  ribbon: "-50%"
  buyButtonLink: "https://doity.com.br/devfest-nordeste-2014"
  buyButtonText: "Esgotado"
  ticketContentList: ["Forneça um comprovante", "Receba um ótimo desconto",""]
  validFrom: "2014-08-26T10:00"
  validThrough: "2014-10-10T23:59"
 -
  name: "Standard"
  price: "R$ 50"
  featured: true
  buyButtonLink: "https://doity.com.br/devfest-nordeste-2014"
  buyButtonText: "Esgotado"
  ticketContentList: ["", "Reserve seu ingresso", ""]
  validFrom: "2014-09-10T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Membros de GDG"
  price: "R$ 40"
  ribbon: "-20%"
  buyButtonLink: "https://doity.com.br/devfest-nordeste-2014"
  buyButtonText: "Esgotado"
  ticketContentList: ["Membros de Google Developer Groups", "Recebem descontos!",""]
  validFrom: "2014-08-26T10:00"
  validThrough: "2014-10-10T23:59"
# -
#  name: "Early Bird"
#  price: "R$ 50"
#  ribbon: "Esgotado"
#  #buyButtonLink: "https://doity.com.br/devfest-nordeste-2014"
#  #buyButtonText: "Esgotado!"
#  ticketContentList: ["Compre com antecedência", "Reserve seu ingresso", "E ganhe um brinde!"]
#  validFrom: "2014-08-26T10:00"
#  validThrough: "2014-09-08T23:59"

# Footer
socialLinks:
 - {link: "https://plus.google.com/u/0/+DevfestNEBR/", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=DevfestNE", icon: "twitter"}
 - {link: "https://facebook.com/DevFestNE", icon: "facebook"}
# - {permalink: "http://2014.devfestne.com.br/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://developers.google.com", text: "Google Developers"}
   - {permalink: "/blog/caravanas", text: "Caravanas"}
 -
  title: "Contato"
  links:
   - {link: "mailto:contato@devfestne.com.br", text: "contato@devfestne.com.br"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Código de Conduta"}
   - {link: "https://drive.google.com/folderview?id=0B3hSeItpKYdUTF9fVGhSTWI5NE0&usp=sharing", text: "Media Kit"}

# Blog
blogTitle: "Últimas novidades"
blogCommentsEnabled: true
discusShortName: "devfestnordeste"


# Speakers List Block
showSessions: true
thumbnailsFolder: /img/speakers/

# Team Block
teamBlockTitle: "Sobre nós"
aboutUs: "Ferramentas e produtos do Google se tornaram sinônimo de produtividade e desempenho no mundo online. O número de inovações tecnológicas e indústrias de TI em que o Google está criando novas ferramentas e produtos é enorme. É difícil conhecer todos eles. É por isso que as pessoas começaram a se reunir em pequenos grupos locais e partilharam a sua experiência com tais produtos. Mais tarde, os seguintes grupos foram chamados Grupos de Desenvolvedores do Google. GDGs podem assumir muitas formas - de apenas algumas pessoas que se juntam para assistir alguns vídeos, para grandes encontros com demonstrações, palestras técnicas, hackathons e conferências."

# Logistics Find Way Block
findWayTitle: "Encontre seu caminho"
logisticsMapCenterCoordinates: "-10.976712,-37.040825,17"
logisticsMapMobileCenterCoordinates: "-10.976712,-37.040825,17"

# Logistics Direction Details Block
directionDetailsTitle: "Ande por Aracaju"
directionDetailsCards:
 - {title: "Do Aeroporto", information: 'O aeroporto é bem próximo. É facilmente acessível por carro, ônibus ou taxi. Mais informações estarão disponíveis em breve.'}
 - {title: "De ônibus", information: 'Aracaju é uma cidade acessível. Qualquer dúvida, fale conosco.'}
 - {title: "Hotéis", information: 'A Orla de Atalaia tem vários hotéis e pousadas disponíveis vizinho ao evento. Mais informações em breve'}
directionDetailsWideCards:
 -
  title: "Perguntas?"
  subCards:
   -
    title: "Hotéis"
    links:
     - {link: "https://plus.google.com/+GDGAracajuBlogspotBR/about", text: "GDG Aracaju"}
     - {link: "https://plus.google.com/+EulerNetoNgt/posts", text: "Euler Neto"}
     - {link: "mailto:contato@devfestne.com.br", text: "Email"}
   -
    title: "Inscrições"
    links:
    - {link: "https://plus.google.com/+GDGAracajuBlogspotBR/about", text: "GDG Aracaju"}
    - {link: "https://plus.google.com/+ErickMendonca/about", text: "Erick Mendonça"}
    - {link: "mailto:contato@devfestne.com.br", text: "Email"}
   -
    title: "Detalhes para participantes"
    links:
    - {link: "https://plus.google.com/+GDGAracajuBlogspotBR/about", text: "GDG Aracaju"}
    - {link: "mailto:contato@devfestne.com.br", text: "Email"}


# Schedule Block
#scheduleWarning: "Observação: a programação ainda pode sofrer alterações sem aviso prévio."
scheduleWarning: ""
